name: 'Validate `composer.json` file'
on:
  push:
  pull_request:
permissions:
  contents: 'read'
jobs:
  main:
    name: 'Validate `composer.json` file'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - name: 'Execute validation command'
        run: 'composer validate --strict --no-check-version'
